export const SET_ALL_TRACKS = "SET_ALL_TRACKS";
export const SET_IS_PLAYING = "SET_IS_PLAYING";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const SET_NEXT_TRACK = "SET_NEXT_TRACK";
export const SET_PREV_TRACK = "SET_PREV_TRACK";
export const TOGGLE_SHUFFLE_TRACKS = "TOGGLE_SHUFFLE_TRACKS";