export const SET_PLAYING_TRACK = "SET_PLAYING_TRACK";
export const PLAYING_TRACK = "PLAYING_TRACK";
export const SET_IS_PLAYING = "SET_IS_PLAYING";

export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
export const TOGGLE_SHUFFLED = "TOGGLE_SHUFFLED";